### ISSUE TITLE
Patch

### ISSUE THREAD

**Issue by hyperxpro** [codingchili/vertx-brotli-reproducer#2]
Hey!

I was tracking Brotli4j issues and I saw this.

Currently, there is a bug in Netty BrotliEncoder in which buffers were compressed in single-shot instead of stream compression. I'm not sure if this issue actually relates to it but I would encourage you to have a look at https://github.com/netty/netty/pull/12924.

Do let me know If I can help. :)

Regards
Aayush Atharva

**Comment by codingchili** [comment]
Hello, thanks for the ping!

Your fix indeed solves this issue, perfect! 

version 4.1.x of vert.x uses netty 4.1.89 which includes the fix, all tests pass.
